Refacto
itheof/lib42 pull request #14
Opened 2016-10-14 15:16 UTC by Kerollmops

- `t_buffer` become `t_string`
- `t_string` and `t_array` looses there big ugly macros

2016-10-14 15:50 UTC, Otaekek commented on src/array/array_create_node.c
>  {
Vraiment utile ?

2016-10-14 15:52 UTC, Otaekek commented on src/array/array_init.c
> -t_array	*array_new(size_t size, size_t elem_size)
remet ca stp

2016-10-14 15:56 UTC, tmielcza commented on src/array/array_create_node.c
> +	if (TARRAY_NEED_RESIZE(v) && array_resize(v) == NULL)
Non mais ça quoi ...

2016-10-14 15:57 UTC, Otaekek commented on src/array/array_insert.c
> +t_array		*array_insert(t_array *v, size_t i, const void *e)
array insert at ?

2016-10-14 15:57 UTC, tmielcza commented on src/array/array_destroy.c
> +void		array_destroy(t_array *v)
?

2016-10-14 15:58 UTC, Otaekek commented on src/array/array_remove.c
>  	char	*p;
`array_remove_at` ?

2016-10-14 15:59 UTC, Otaekek commented on src/array/array_replace.c
> +void	*array_replace(t_array *v, size_t i, const void *e, void *old)
same

2016-10-14 16:00 UTC, Otaekek commented on src/array/array_replace.c
> +		p = TARRAY_GET(v, i); // TODO array_get_at ??
tout doux.

2016-10-14 16:03 UTC, Kerollmops commented on src/array/array_destroy.c
> +void		array_destroy(t_array *v)
Cette function doit être repensée, avec la nouvelle refacto, toutes les fonction travaillent avec un pointeur en entrée donc, soit cette fonction disparait soit elle doit être éclaircie/renommée

2016-10-14 16:22 UTC, itheof commented on test/src/array/test_array_push.c
> +	array_init(&array, 8, elem_size);
Du coup comme on reste a la meme adresse il serait bien de scribble la variable array avant de l'init par les fonctions testees.

2016-10-14 16:22 UTC, tmielcza commented on src/string/string_insert.c
> +	if (STRING_NEED_RESIZE(s, l) && priv_string_resize(s, l) == NULL)
priv ?

2016-10-14 16:24 UTC, Kerollmops commented on src/string/string_insert.c
> +	if (STRING_NEED_RESIZE(s, l) && priv_string_resize(s, l) == NULL)
Il ne faut pas l'utiliser de l'extérieur (un include interne à la lib serait propre mais embêtant niveau Makefile, pas tant que ça en fait)

2016-10-14 16:25 UTC, Kerollmops commented on src/string/string_insert.c
> +	if (STRING_NEED_RESIZE(s, l) && priv_string_resize(s, l) == NULL)
En fait `priv_string_resize` pourrait être remplacée

2016-10-14 16:34 UTC, tmielcza commented on src/string/string_truncate.c
> +ssize_t		string_truncate(t_string *s, size_t n)
Pourquoi pas juste une fonction resize? C'est plus générique.

2016-10-14 16:35 UTC, Kerollmops commented on src/string/string_truncate.c
> +ssize_t		string_truncate(t_string *s, size_t n)
Elle existe mais elle est privée (i.e. [priv_string_resize.c](https://github.com/itheof/lib42/blob/refacto/src/string/priv_string_resize.c))

2016-10-14 17:34 UTC, Kerollmops commented on src/array/array_create_node.c
>  {
Il parle de la fonction `array_create_node`

2016-10-14 17:36 UTC, Kerollmops commented on src/array/array_create_node.c
> +	if (TARRAY_NEED_RESIZE(v) && array_resize(v) == NULL)
Je suis d'accord, je pense implémenter une fonction qui fais le job toute seul, pas deux conditions, utiliser `t_array *array_reserve(t_array *array, size_t n)` serait une très bonne solution je trouve

2016-10-14 17:40 UTC, Kerollmops commented on test/src/array/test_array_push.c
> +	array_init(&array, 8, elem_size);
la fonction testée ici n'est pas `array_init` mais `array_push`, je ferais du `memset(UNSIGNED_CHAR_MAX)` lors des test de `array_init`

2016-10-14 17:44 UTC, tmielcza commented on src/string/string_truncate.c
> +ssize_t		string_truncate(t_string *s, size_t n)
Pourquoi ?

2016-10-14 17:46 UTC, Kerollmops commented on src/string/string_truncate.c
> +ssize_t		string_truncate(t_string *s, size_t n)
@dkrmr (invocation)
Je trouve que cette fonction ainsi que la macro `STRING_NEED_RESIZE` devraient être remplacées par la fameuse fonction `string/array_reserve` !

2016-10-14 17:47 UTC, tmielcza commented on src/array/array_create_node.c
> +	if (TARRAY_NEED_RESIZE(v) && array_resize(v) == NULL)
C'est juste que si on commence tous à reformater les morceaux de code qui nous plaisent pas, on va pas s'en sortir. Après si c'était un problème de norme, je dis rien. Mais dans ce cas y'a intérêt que tout le reste passe.

2016-10-14 18:02 UTC, tmielcza commented on src/array/array_destroy.c
> +void		array_destroy(t_array *v)
Non mais le tab.

2016-10-14 18:06 UTC, Kerollmops commented on src/array/array_create_node.c
>  {
@dkrmr (invocation)

2016-10-14 19:37 UTC, Kerollmops commented on src/array/array_destroy.c
> +void		array_destroy(t_array *v)
On s'en fout sérieux, j'en sais rien !

2016-10-14 20:59 UTC, Kerollmops commented
Je vais aussi ajouter les fonctions `string/array_shrink_to_fit` qui permette de rapprocher la `capacity` au plus proche de la `len`, consommer moins de ram !

@dkrmr je ne comprend pas pourquoi `t_string` ne contient tout simplement pas un `t_buffer`, on limiterais le nombre de fonctions à tester. la compilation n'en serait que plus rapide et toutes les fonctionnalités seraient disponible et en un seul exemplaire.

2016-10-14 21:25 UTC, Kerollmops commented
`string_init` ne devrait pas avoir de paramètre de size, `string_init_capacity` oui.
Je pense qu'elle devrait gérer ça en interne jusqu'au bout, si elle doit le faire seule, pourquoi doit t'on lui spécifier quoi que se soit à l'init ?

2016-10-14 22:28 UTC, Kerollmops commented on src/string/string_insert.c
> +	if (STRING_NEED_RESIZE(s, l) && priv_string_resize(s, l) == NULL)
Elle vient d'être remplacée par `string_reserve`

2016-10-14 22:30 UTC, Kerollmops commented on src/string/string_truncate.c
> +ssize_t		string_truncate(t_string *s, size_t n)
fait ✅

2016-10-15 14:33 UTC, Kerollmops commented
Le comportement des fonctions `string_stoa` et `string_utoa` doit être précisé, actuellement elles concatènent le chiffre dans une string. Je pense qu'elles devraient soit changer de nom (`string_cat_stoa` et `string_cat_utoa`), soit changer de comportement et simplement initialiser une string un le chiffre.

2016-10-15 16:42 UTC, tmielcza commented
[Pour ça](https://github.com/itheof/lib42/pull/14#issuecomment-253917865) je sais pas. Si tu veux. [Pour ça](https://github.com/itheof/lib42/pull/14#issuecomment-253987770) le mieux serait d'utiliser des formateurs genre printf. Et sinon oui, les noms sont à chier.

2016-10-15 16:44 UTC, Kerollmops commented
En fait printf se sert de ces deux fonctions `string_stoa` et `string_utoa`.

2016-10-15 20:05 UTC, Kerollmops commented
En fin de compte mettre un `t_array` dans la `t_string` n'est pas une bonne idée au niveau de la complexité d'utilisation du `t_array`. Le `t_array` demande de gérer un `void*` alors que la `t_string` n'est qu'un `char*` simple.

2016-10-16 09:47 UTC, Kerollmops commented
Merci @dkrmr de m'avoir montré que `string_reserve` devrais faire le fameux +1 (**\0**), ce ne sont pas aux fonctions du dessus de le faire, c'est encore une fois semi historique, c'est une erreur qui doit être réglée !

2016-10-16 13:00 UTC, Kerollmops commented
Bon vas falloir clarifier les fonctions `ssize_t array_index_of(t_array *a, const void *e)` et `void *array_remove_elem(t_array *a, const void *e)` qui ne trouve/supprime pas le premier élément qui match mais qui a la même adresse... A moins que ce soit clair pour tout le mone 😸

2016-10-16 15:51 UTC, Kerollmops commented
J'ai ajouté aux EDITs les liens de comparaisons pour ne pas vous en montrer trop d'un coup ! 🍭

2016-10-17 08:50 UTC, dariuskramer commented on src/array/array_create_node.c
>  {
La fonction `array_create_node` permet de créer un espace dans le tableau et renvoie le pointeur vers la case libre. Imaginons que tu stocke des structures dans le tableau, 2 cas de figure pour peupler ton tableau:
- 1: Tu créer une structure sur la stack, ou mallocé, tu la remplis, tu la push dans le tableau qui va `memcpy` son contenu.
- 2: Tu demande un node avec `array_create_node`, il te renvoit un pointeur vers la nouvelle case memoire, tu la remplis et voilà. Pas de `memcpy`, vu que la structure fait déjà partie du tableau.

2016-10-17 09:07 UTC, dkrmr commented
Concernant les [(s|u)toa](https://github.com/itheof/lib42/pull/14#issuecomment-253987770), elles étaient des fonctions temporaires pour la prochaine `string_fmt` que je voulais faire, une sorte de mini `printf`.

> array_new and string_new has disappear, do you really want that ? No !

Heu, Yes ! ... Je viens de voir le code, elles ont été renommé `string_create`. Tu aurais juste pu le préciser dans le message: `array/string_new renamed array/string_create`

2016-10-17 09:31 UTC, dkrmr commented on inc/array_42.h
> +** (default size) * elem_size or capacity *elem_size if specified.
Rajouter un espace après `*` pour éviter la confusion avec la notation pointer

2016-10-17 09:38 UTC, dkrmr commented on src/array/array_create.c
> +		free(a);
Si la fonction `array_init` renvoit *NULL*, tu renvoie un pointer qui vient d'etre `free()`

2016-10-17 09:43 UTC, dkrmr commented on src/array/array_create.c
> +	return (NULL);
Ici tu fais un choix des plus... inattendu. La fonction renvoie **NULL**, qu'elle réussisse ou qu'elle échoue ^^

Il faudra compléter les tests avant d'accepter la PR

2016-10-17 09:45 UTC, itheof commented
Manque des tests.

2016-10-17 10:09 UTC, Kerollmops commented
Amusez-vous ! 😺

2016-10-17 10:10 UTC, Kerollmops commented
@dkrmr pour les function `*_create_*` c'est dans le premier EDIT

2016-10-17 10:29 UTC, Kerollmops commented
Tant que je n'ai pas upvoté ma PR, elle ne peux pas être merge

2016-10-17 10:43 UTC, dkrmr commented on src/array/array_create.c
> +t_array			*array_create(size_t elem_size)
La fonction `array_init` réutilise la fonction `array_init_with_capacity`. Pourquoi ne pas faire de meme ici ?
`return (array_create_with_capacity(elem_size, TARRAY_INIT_SIZE))`
Ça évite la duplication.

2016-10-17 11:55 UTC, dkrmr commented
Les fonctions que tu as renommer de `_new` vers `_create` ne respecte pas la norme du project: https://github.com/itheof/42sh-posix/wiki/Norme#des-mots

2016-10-17 12:01 UTC, Kerollmops commented
Les opposés juste au dessus sont `create/destroy`, il faudrait penser à mettre à jour la norme.
On s'est inspiré de [la norme d'Insomniac games](http://www.insomniacgames.com/core-coding-standard/#id.d45219520876) pour les opposé dont `init/shutdown`, je ne suis pas fan non plus, j'ai pensé à `deinit` mais c'est pas très bon non plus.

2016-10-17 12:05 UTC, dkrmr commented
En effet il faut update la norme en conséquence. Soit on garde le couple `create/destroy` soit `new/destroy`. Summon @tmielcza.

2016-10-17 12:14 UTC, dkrmr commented on src/array/array_reserve.c
> +	if (a->capacity - a->len < additional)
Est-ce que `(a->len + additional > a->capacity)` n'est pas plus censé à lire ?

2016-10-17 12:18 UTC, dkrmr commented on src/array/array_shrink_to_fit.c
> +			capacity = TARRAY_INIT_SIZE;
Éviter un appel de fonction:
```
if (a->len < TARRAY_INIT_SIZE)
    capacity = TARRAY_INIT_SIZE;
else
    capacity = next_power_of_2(a->len);
```

2016-10-17 12:22 UTC, dariuskramer commented on src/array/array_truncate.c
> +ssize_t		array_truncate(t_array *a, size_t n)
Si `n == a->len` tu renvoie **-1**. Est-ce souhaité ?
Dans ton commentaire du défini la valeur de retour comme:

> It returns the new size of the string or -1 if the truncate is to large.

Une troncature sur la taille exacte est-elle considéré comme trop large ?

2016-10-17 12:24 UTC, dkrmr commented on src/array/array_clone.c
> +t_array		*array_copy(t_array *dst, const t_array *src)
Erreur de typo, la fonction s'appelle toujours `copy` au lieu de `clone`.
Le prototype dans le header est lui correct.

2016-10-17 12:27 UTC, dkrmr commented on src/array/array_clone.c
> +t_array		*array_copy(t_array *dst, const t_array *src)
De plus, pour appeler la fonction `array_clone` il faut fournir la structure `t_array *dst`. Ne devrait-elle pas se charger de l'allocation de la structure ?
Le but de la fonction sera de simplement l'appeler et de récupérer un pointeur. La il faut au préalable, soit créer la structure sur la stack et envoyer son adresse, soit la malloc.
Je trouve ça pas adapté. On devrait juste recevoir le clone et ne pas se charger de l'allocation.

2016-10-17 12:32 UTC, dkrmr commented on src/array/array_index_of.c
> +	if (e >= a->data && (size_t)e < (size_t)a->data + a->len * a->elem_size)
Voila pourquoi j'ai crée une macro. C'est quand meme bien plus simple de comprendre ce que la ligne fait avec une macro. On peut éclaircir son nom pour etre plus explicite:
`ADDR_IN_DATA_RANGE(v, e)`

Je trouve ça plus explicite que `e >= a->data && (size_t)e < (size_t)a->data + a->len * a->elem_size`.
L'un est clairement plus simple à comprendre au premier coup d'oeil que l'autre.

2016-10-17 12:34 UTC, dkrmr commented on src/array/array_index_of.c
> +	if (e >= a->data && (size_t)e < (size_t)a->data + a->len * a->elem_size)
Également, il est préférable d'utiliser le type `uintptr_t` pour le cast de pointeur en valeur arithmétique.

2016-10-17 12:46 UTC, dariuskramer commented on src/array/array_index_of.c
> +		index = (size_t)e - (size_t)a->data;
Comme je te l'avais déjà dit, l'arithmétique de pointeur a comme type `ptrdiff_t`. C'est un type signé.
La méthode la plus respectable du standard:

```
ptrdiff_t diff = (char*)e - (char*)v->data;
index /= (size_t)diff;
```

Au pire:
`index = (uintptr_t)e - (uintptr_t)a->data`

2016-10-17 12:56 UTC, Kerollmops commented on src/array/array_reserve.c
> +	if (a->capacity - a->len < additional)
si mais tu peux overflow 😢

2016-10-17 13:01 UTC, Kerollmops commented on src/array/array_shrink_to_fit.c
> +			capacity = TARRAY_INIT_SIZE;
Plutôt ça:
```c
if (a->len <= TARRAY_INIT_SIZE)
    capacity = TARRAY_INIT_SIZE;
else
    capacity = next_power_of_2(a->len);
```
mais oui

2016-10-17 13:03 UTC, Kerollmops commented on src/array/array_truncate.c
> +ssize_t		array_truncate(t_array *a, size_t n)
heu non, j'ai récupéré le `string_truncate`, c'est une erreur merci !

2016-10-17 13:05 UTC, Kerollmops commented on src/array/array_truncate.c
> +ssize_t		array_truncate(t_array *a, size_t n)
Heu attend ! à quel moment ?
```c
if (n > a->len)
     return (-1);
```

2016-10-17 13:10 UTC, Kerollmops commented on src/array/array_clone.c
> +t_array		*array_copy(t_array *dst, const t_array *src)
Non je ne pense pas que se soit voulu par l'utilisateur, un malloc n'est pas forcement nécéssaire. Comme tu dis si l'utilisateur veux un malloc, il malloc sa structure au dessus et laisse cette fonction l'initialiser.

2016-10-17 13:12 UTC, Kerollmops commented on src/array/array_index_of.c
> +	if (e >= a->data && (size_t)e < (size_t)a->data + a->len * a->elem_size)
Cette macro ne serait appelé **qu'une seule et unique fois** dans toute la library d'où l'inutilité d'une macro.

Je vais changer le cast en `uintptr_t` par contre

2016-10-17 13:15 UTC, Kerollmops commented on src/array/array_index_of.c
> +		index = (size_t)e - (size_t)a->data;
J'ai changé, dit moi si ça te plais

2016-10-17 13:35 UTC, Kerollmops commented on src/array/array_reserve.c
> +	if (a->capacity - a->len < additional)
C'est bête parce qu'à l'intérieur je fais `a->len + additional` aussi, donc bon...

2016-10-17 13:39 UTC, dariuskramer requested changes

2016-10-17 13:39 UTC, dkrmr commented on src/array/array_stack.c
> +	return (array_remove_at(a, a->len, old));
Tu réduis la `len` de 1 mais `array_remove_at` aussi. Donc tu viens d'enlever 2 élément. :)

2016-10-17 13:40 UTC, dkrmr commented on src/array/array_truncate.c
> +ssize_t		array_truncate(t_array *a, size_t n)
O_o my bad, j'ai du halluciner.

2016-10-17 13:41 UTC, dariuskramer commented on src/array/array_reserve.c
> +	if (a->capacity - a->len < additional)
De toute façon si ça overflow on ne peut pas faire grand chose... On est déjà avec les types qui ont des sizes maximum.

2016-10-17 13:42 UTC, Kerollmops commented on src/array/array_stack.c
> +	return (array_remove_at(a, a->len, old));
He ouai ! faut des tests unitaires ! merci 😄

2016-10-17 13:42 UTC, dkrmr commented on src/array/array_index_of.c
> +	if (e >= a->data && (size_t)e < (size_t)a->data + a->len * a->elem_size)
Et alors ? Qu'elle importance qu'elle soit appelé une seule fois ?
Le but d'une macro c'est aussi d'augmenter la clarté. Et là clairement ce serait une nécessité.

2016-10-17 13:51 UTC, dariuskramer commented on src/array/array_index_of.c
> +		index = (size_t)e - (size_t)a->data;
On fait un peu n'importe quoi avec les types mais c'est pas grave ^^'

2016-10-17 13:54 UTC, dkrmr commented on src/array/array_stack.c
>  	a->len -= 1;
Tu fais la meme chose qu'avant. Supprimer totalement la ligne `a->len -= 1`, la fonction `array_remove_at` s'en charge deja.

2016-10-17 13:57 UTC, Kerollmops commented
Je vais changer le prototype de `array_pop` il renverra un `t_array *` comme toutes les autres fonctions !

2016-10-17 13:58 UTC, dariuskramer commented on src/string/string_init.c
> +	if ((s->str = malloc(sizeof(char) * s->capacity)) == NULL)
Tu peux retirer le `sizeof(char)`, ça renvoit toujours 1 et c'est garantie par le standard:
[6.5.3.4 The sizeof operator](http://port70.net/%7Ensz/c/c99/n1256.html#6.5.3.4)

> When applied to an operand that has type char, unsigned char, or signed char, (or a qualified version thereof) the result is 1.

2016-10-17 14:12 UTC, dkrmr commented
Pourquoi vouloir modifier le prototype de `array_pop` ?
Quand on veut pop un élément on veut le récupérer.

2016-10-17 14:16 UTC, dkrmr commented on src/string/string_dup.c
> +	cpy_stop = ft_memccpy(s->str, str, '\0', len);
Pourquoi faire un `memccpy` ?

2016-10-17 14:18 UTC, dariuskramer commented on src/string/string_dup.c
> +	s->len = cpy_stop == NULL ? len : (size_t)(cpy_stop - 1 - s->str);
Le ternaire je ne suis pas fan, surtout qu'il est moins clair.

```
if (cpy_stop == NULL)
    s->len = len;
else
    s->len = (size_t)(cpy_stop - 1 -s->str);
```

2016-10-17 14:24 UTC, dkrmr commented on src/string/string_replace.c
> +#include <stdio.h> // delete
Tu peux le supprimer maintenant je pense

2016-10-17 14:52 UTC, dariuskramer commented on src/array/array_create_node.c
>  {
Nouveau nom (Merci à Céline @cdann): `array_get_available` !

2016-10-17 15:06 UTC, Kerollmops commented
Je vais implémenter la nouvelle fonction `string_get_available`

2016-10-17 15:25 UTC, dkrmr commented on src/string/string_remove.c
> +	s->str[pos] = '\0';
Utiliser `array_remove_back` plutot que de refaire du code.

2016-10-17 16:13 UTC, dkrmr commented on src/array/array_index_of.c
> +	if (e >= a->data && (size_t)e < (size_t)a->data + a->len * a->elem_size)
```
#define ADDR_LIMIT(a) ((uintptr_t)((a)->data + (a)->len * (a)->elem_size))
#define ADDR_IN_DATA_RANGE(a, e) ((e) >= (a)->data && (e) < ADDR_LIMIT(a))
```

Je le concède... c'est dégueu...

2016-10-17 16:14 UTC, dariuskramer approved these changes

2016-10-18 16:39 UTC, dkrmr commented
Il ne manque plus que virer les leaks de l'executable de test et on est bon.

2016-10-19 10:01 UTC, dkrmr commented
Les leaks sont officiellements enlevés ! Merci à @itheof pour le `getopt`

2016-10-19 11:55 UTC, merged