Cbuffer updates (to fit the norm)
itheof/lib42 pull request #17
Opened 2016-10-20 15:32 UTC by Kerollmops

2016-10-22 09:20 UTC, dariuskramer requested changes

2016-10-22 09:20 UTC, dkrmr commented on src/cbuffer/cbuffer_init.c
> +void		cbuffer_shutdown(t_cbuffer *buffer)
Le commentaire au-dessus du prototype indique que tu `free()` le buffer interne, mais je pense que tu as oublié de le faire.
D'ou l'intéret de faire les tests et de lancer **valgrind** ensuite sur le binaire de test.
Apparemment tu n'as pas fait de test pour les fonctions de création/initialisation.

2016-10-22 09:22 UTC, dkrmr commented on src/cbuffer/cbuffer_reserve_shrink.c
> +		b->end = b->len == 0 ? 0 : b->len - 1;
Ajouter des parenthèses aux ternaires pour augmenter la lisibilité:
`b->end = (b->len == 0) ? 0 : (b->len - 1);`

2016-10-22 09:29 UTC, dkrmr commented on src/cbuffer/cbuffer_truncate.c
> +t_cbuffer	*cbuffer_truncate_from_back(t_cbuffer *buffer, size_t n)
Le code de ces 2 fonctions est identique, sauf pour l'appel de fonction `_pop_`.
Une petite refacto ?
```

static void	*cbuffer_truncate_from(t_cbuffer *buffer, size_t n,
		void *(*pop_method)(t_cbuffer *))
{
	size_t	to_pop;
	void	*popped;

	if (n > buffer->len)
		return (NULL);
	to_pop = buffer->len - n;
	while (to_pop != 0)
	{
		popped = (*pop_method)(buffer);
		if (buffer->delete_func != NULL)
			buffer->delete_func(popped);
		--to_pop;
	}
	return (buffer);
}

t_cbuffer	*cbuffer_truncate_from_back(t_cbuffer *buffer, size_t n)
{
	cbuffer_truncate_from(buffer, n, &cbuffer_pop_back);
	return (buffer);
}

t_cbuffer	*cbuffer_truncate_from_front(t_cbuffer *buffer, size_t n)
{
	cbuffer_truncate_from(buffer, n, &cbuffer_pop_front);
	return (buffer);
}
```

2016-10-22 09:34 UTC, dariuskramer requested changes
Les tests unitaires sont pour le moment insuffisant et surtout les fonctions de setup/teardown doivent etre utilisé et correctement encapsuler pour ne pas utiliser des fonctions à tester.

2016-10-22 09:35 UTC, Kerollmops commented on src/cbuffer/cbuffer_init.c
> +void		cbuffer_shutdown(t_cbuffer *buffer)
valgrind ne fonctionne pas à l'ecole ni sur mon mac et leaks par en boucle inf aussi, je l'aurait bien fais si ça avait marché....

2016-10-22 09:37 UTC, dkrmr commented on src/cbuffer/cbuffer_init.c
> +void		cbuffer_shutdown(t_cbuffer *buffer)
Ah merde :/

2016-10-25 15:56 UTC, Kerollmops commented on src/cbuffer/cbuffer_init.c
> +void		cbuffer_shutdown(t_cbuffer *buffer)
En fait c'est juste `SANITIZE`

2016-10-26 07:05 UTC, dariuskramer approved these changes

2016-10-28 16:11 UTC, merged